/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BacklogIndexRouteImport } from './routes/backlog/index'
import { Route as BacklogItemsItemRouteImport } from './routes/backlog/$items/item'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BacklogIndexRoute = BacklogIndexRouteImport.update({
  id: '/backlog/',
  path: '/backlog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BacklogItemsItemRoute = BacklogItemsItemRouteImport.update({
  id: '/backlog/$items/item',
  path: '/backlog/$items/item',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/backlog': typeof BacklogIndexRoute
  '/backlog/$items/item': typeof BacklogItemsItemRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/backlog': typeof BacklogIndexRoute
  '/backlog/$items/item': typeof BacklogItemsItemRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/backlog/': typeof BacklogIndexRoute
  '/backlog/$items/item': typeof BacklogItemsItemRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/backlog' | '/backlog/$items/item'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/backlog' | '/backlog/$items/item'
  id: '__root__' | '/' | '/backlog/' | '/backlog/$items/item'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BacklogIndexRoute: typeof BacklogIndexRoute
  BacklogItemsItemRoute: typeof BacklogItemsItemRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backlog/': {
      id: '/backlog/'
      path: '/backlog'
      fullPath: '/backlog'
      preLoaderRoute: typeof BacklogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backlog/$items/item': {
      id: '/backlog/$items/item'
      path: '/backlog/$items/item'
      fullPath: '/backlog/$items/item'
      preLoaderRoute: typeof BacklogItemsItemRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BacklogIndexRoute: BacklogIndexRoute,
  BacklogItemsItemRoute: BacklogItemsItemRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
